### ISSUE TITLE
Unauthorized tests failed in nightly build

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/owncloud-sdk#1176] opened 2022-11-10 08:17 UTC
Build: https://drone.owncloud.com/owncloud/owncloud-sdk/3933/7/5

```
PASS tests/signedUrlIntegrationTest.js
FAIL tests/unauthorized/appsTest.js
  ● Unauthorized: Currently testing apps management, › checking method : getApps

    Mock server failed with the following mismatches:

      0) The following request was expected but not received: 
          Method: GET
          Path: /ocs/v1.php/cloud/apps
          Query String: filter=enabled
          Headers:
            authorization: Basic YWRtaW46bm90QVZhbGlkUGFzc3dvcmQ=

      59 |     await getAppsInvalidAuthInteraction(provider, { filter: 'enabled' })
      60 |
    > 61 |     await provider.executeTest(async () => {
         |     ^
      62 |       const oc = createOwncloud(adminUsername, config.invalidPassword)
      63 |       await oc.login().then(() => {
      64 |         fail('not expected to log in')

      at node_modules/@pact-foundation/src/v3/pact.ts:243:17
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (tests/unauthorized/appsTest.js:61:5)
```

**Comment by saw-jan** [comment] 2022-11-18 06:10
Couldn't reproduce it so I couldn't think of any issues causing this error

**Comment by saw-jan** [comment] 2022-12-12 06:57
Haven't seen this failure lately
Closing now!

**Closed by saw-jan** 2022-12-12 06:57 UTC
Labels: QA:team
